riscv64-unknown-elf-gcc.exe test.c  -nostdlib -T link_simple.ld -march=rv32if -mabi=ilp32f  -o test.elf
riscv64-unknown-elf-objdump.exe -D test.elf  > test.txt
./extract_hex.sh test.elf imem.hex dmem.hex
riscv64-unknown-elf-objdump.exe -s -j .rodata test.elf | sed '1,4d' > temp_dmem.txt




